### ISSUE TITLE
 Repository not found

### ISSUE THREAD

**Issue by dreamcatcher45** [msafeerhussain/canva-clone-project#1]
git clone https://github.com/msafeerhussain/canva-clone.git  is not able to find the repo...it shows " Repository not found."

**Comment by msafeerhussain** [comment]
Hey Jerome George,
The repo is private now due to some reasons.

**Comment by dreamcatcher45** [comment]
> Hey Jerome George,
> The repo is private now due to some reasons.
> 
> > Message ID: ***@***.***>
> >
> 

Ok👍
